kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: tpt-kafka-manager
  namespace: appsec
  labels:
    team: appsec
spec:
  image: europe-north1-docker.pkg.dev/nais-management-233d/poao/kafka-manager:2026.01.08-11.18-235a0f4
  port: 8080
  ingresses:
    - https://tpt-kafka-manager.intern.nav.no
  readiness:
    path: /internal/health/readiness
    initialDelay: 20
  liveness:
    path: /internal/health/liveness
    initialDelay: 20
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 75
  resources:
    limits:
      cpu: "1"
      memory: 1024Mi
    requests:
      cpu: 250m
      memory: 512Mi
  azure:
    application:
      enabled: true
      tenant: nav.no
      claims:
        groups:
          - id: d633d27b-a470-4b9d-984e-85499f126e18
    sidecar:
      enabled: true
  kafka:
    pool: nav-prod
  env:
    - name: APP_CONFIG_JSON # Required
      value: >
        {
          "topics": [
            {
              "name": "appsec.tpt",
              "location": "AIVEN",
              "keyDeserializerType": "STRING",
              "valueDeserializerType": "STRING"
            }
          ]
        }