apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: appsec-guide
  namespace: appsec
  labels:
    team: appsec
spec:
  ingresses:
    - https://appsec-guide.intern.nav.no
  azure:
    application:
      enabled: true
      allowAllUsers: true
      claims:
        groups:
          - id: "d633d27b-a470-4b9d-984e-85499f126e18"
        extra:
          - "NAVident"
    sidecar:
      enabled: true
      autoLogin: true
  accessPolicy:
    outbound:
      external:
        - host: console.nav.cloud.nais.io
  valkey:
    - instance: appsec
      access: readwrite
  image: {{image}}
  port: 8080
  liveness:
    initialDelay: 30
    path: isalive
  readiness:
    initialDelay: 30
    path: isready
  replicas:
    max: 2
    min: 2
  resources:
    limits:
      memory: 256Mi
    requests:
      cpu: 50m
      memory: 64Mi
  observability:
    logging:
      destinations:
        - id: loki
  env:
    - name: NAIS_API_URL
      value: "https://console.nav.cloud.nais.io/graphql"
    - name: CACHE_TTL_MINUTES
      value: "60"
  envFrom:
    - secret: appsec-guide