apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: tpt-backend
  namespace: appsec
  labels:
    team: appsec
spec:
  azure:
    application:
      enabled: true
      allowAllUsers: true
      claims:
        groups:
          - id: "d633d27b-a470-4b9d-984e-85499f126e18"
        extra:
          - "NAVident"
  accessPolicy:
    inbound:
      rules:
        - application: tpt-frontend
    outbound:
      rules:
        - application: team-catalog-backend
          namespace: org
      external:
        - host: console.nav.cloud.nais.io
        - host: www.cisa.gov
        - host: api.first.org
        - host: services.nvd.nist.gov
  valkey:
    - instance: appsec
      access: readwrite
  gcp:
    sqlInstances:
      - type: POSTGRES_17
        tier: db-g1-small
        databases:
          - name: tpt
  image: {{image}}
  port: 8080
  leaderElection: true
  liveness:
    initialDelay: 10
    path: isalive
  readiness:
    initialDelay: 10
    path: isready
  replicas:
    max: 2
    min: 2
  resources:
    limits:
      memory: 512Mi
    requests:
      cpu: 48m
      memory: 256Mi
  observability:
    logging:
      destinations:
        - id: loki
  env:
    - name: NAIS_API_URL
      value: "https://console.nav.cloud.nais.io/graphql"
    - name: NVD_API_URL
      value: "https://services.nvd.nist.gov/rest/json/cves/2.0"
    - name: EPSS_API_URL
      value: "https://api.first.org/data/v1"
    - name: TEAMKATALOGEN_URL
      value: "http://team-catalog-backend.org"
    - name: CACHE_TTL_MINUTES
      value: "15"
  envFrom:
    - secret: tpt-backend
