apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: tpt-backend
  namespace: appsec
  labels:
    team: appsec
spec:
  azure:
    application:
      enabled: true
      allowAllUsers: true
      claims:
        groups:
          - id: "d633d27b-a470-4b9d-984e-85499f126e18"
        extra:
          - "NAVident"
  ingresses:
    - https://tpt-backend.intern.nav.no
  accessPolicy:
    inbound:
      rules:
        - application: tpt-frontend
    outbound:
      external:
        - host: console.nav.cloud.nais.io
        - host: www.cisa.gov
        - host: api.first.org
  valkey:
    - instance: appsec
      access: readwrite
  image: {{image}}
  port: 8080
  liveness:
    initialDelay: 10
    path: isalive
  readiness:
    initialDelay: 10
    path: isready
  replicas:
    max: 2
    min: 2
  resources:
    limits:
      memory: 256Mi
    requests:
      cpu: 21m
      memory: 192Mi
  observability:
    logging:
      destinations:
        - id: loki
  env:
    - name: NAIS_API_URL
      value: "https://console.nav.cloud.nais.io/graphql"
    - name: CACHE_TTL_MINUTES
      value: "60"
  envFrom:
    - secret: tpt-backend
