name: Build and deploy main
on:
  push:
    branches:
      - main
    paths-ignore:
      - "*.md"
  pull_request:
jobs:
  test-build:
    permissions:
      actions: read # for sarif
      contents: write # for dependency graph & sarif
      id-token: write # for nais docker-build-push
    runs-on: ubuntu-latest
    outputs:
      image: ${{ steps.docker-push.outputs.image }}
    steps:
      - uses: actions/checkout@v6.0.1
        with:
          persist-credentials: false
      - uses: actions/setup-java@v5
        with:
          java-version: 25
          distribution: temurin
      - uses: gradle/actions/setup-gradle@50e97c2cd7a37755bbfafc9c5b7cafaece252f6e
      - name: Test & build
        run: ./gradlew test installDist
      - name: Build & push docker image + SBOM
        uses: nais/docker-build-push@cd5ec5663feb0e05c3fa374d1fb442605b046c6b
        id: docker-push
        with:
          team: appsec
          pull: true
          push_image: ${{ github.ref == 'refs/heads/main' }}
      - name: Generate and submit dependency graph
        if: github.ref == 'refs/heads/main'
        uses: gradle/actions/dependency-submission@50e97c2cd7a37755bbfafc9c5b7cafaece252f6e

  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    permissions:
      contents: read
      id-token: write
    needs: test-build
    steps:
      - uses: actions/checkout@v6.0.1
        with:
          persist-credentials: false
      - uses: nais/deploy/actions/deploy@fa754451577294aae42872a69b888b3470478ec1
        env:
          RESOURCE: .nais/nais.yaml
          CLUSTER: prod-gcp
          IMAGE: ${{ needs.test-build.outputs.image }}

  trivy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    permissions:
      id-token: write
      contents: write # for dependency graph & sarif
      security-events: write # push sarif to github security
    needs: test-build
    steps:
      - uses: nais/login@v0
        with:
          team: appsec
      - name: Scan docker image for secrets
        uses: aquasecurity/trivy-action@57a97c7e7821a5776cebc9bb87c984fa69cba8f1
        with:
          image-ref: '${{ needs.test-build.outputs.image }}'
          format: 'sarif'
          scanners: 'secret'
          output: 'trivy.sarif'
      - uses: github/codeql-action/upload-sarif@95e58e9a2cdfd71adc6e0353d5c52f41a045d225
        with:
          sarif_file: 'trivy.sarif'