name: Build and deploy main
on:
  push:
    branches:
      - main
    paths-ignore:
      - "*.md"
  pull_request:
jobs:
  test-build:
    permissions:
      actions: read # for sarif
      contents: write # for dependency graph & sarif
      id-token: write # for nais docker-build-push
    runs-on: ubuntu-latest
    outputs:
      image: ${{ steps.docker-push.outputs.image }}
    steps:
      - uses: actions/checkout@v6.0.1
        with:
          persist-credentials: false
      - uses: actions/setup-java@v5
        with:
          java-version: 25
          distribution: temurin
      - uses: gradle/actions/setup-gradle@50e97c2cd7a37755bbfafc9c5b7cafaece252f6e
      - name: Test & build
        run: ./gradlew test installDist
      - name: Build & push docker image + SBOM
        uses: nais/docker-build-push@751a312f0803eb96a05a41fadf51be19b7be362c
        id: docker-push
        with:
          team: appsec
          pull: true
          push_image: ${{ github.ref == 'refs/heads/main' }}
      - name: Generate and submit dependency graph
        if: github.ref == 'refs/heads/main'
        uses: gradle/actions/dependency-submission@50e97c2cd7a37755bbfafc9c5b7cafaece252f6e

  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    permissions:
      contents: read
      id-token: write
    needs: test-build
    steps:
      - uses: actions/checkout@v6.0.1
        with:
          persist-credentials: false
      - uses: nais/deploy/actions/deploy@a7f8690f9b367fcbf5348a0a1e21d44f1aae50eb
        env:
          RESOURCE: .nais/nais.yaml
          CLUSTER: prod-gcp
          IMAGE: ${{ needs.test-build.outputs.image }}

  trivy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    permissions:
      id-token: write
      contents: write # for dependency graph & sarif
      security-events: write # push sarif to github security
    needs: test-build
    steps:
      - uses: nais/login@v0
        with:
          team: appsec
      - name: Scan docker image for secrets
        uses: aquasecurity/trivy-action@ed142fd0673e97e23eac54620cfb913e5ce36c25
        with:
          image-ref: '${{ needs.test-build.outputs.image }}'
          format: 'sarif'
          scanners: 'secret'
          output: 'trivy.sarif'
      - uses: github/codeql-action/upload-sarif@68bde559dea0fdcac2102bfdf6230c5f70eb485e
        with:
          sarif_file: 'trivy.sarif'