name: Build and deploy main
on:
  push:
    branches:
      - main
    paths-ignore:
      - "*.md"
  pull_request:
  workflow_dispatch: 
jobs:
  test-build:
    permissions:
      actions: read # for sarif
      contents: write # for dependency graph & sarif
      id-token: write # for nais docker-build-push
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false
      - name: OSSF Scorecard action
        uses: ossf/scorecard-action@v2.4.
        with:
          results_file: output.sarif
          results_format: sarif
          public_results: true
